### ISSUE TITLE
Места приёма врачей не сортируются

### ISSUE THREAD

**Issue by dojekon** [Yuratos/SOUP_system#1]
## Ожидаемое поведение
Места приёма врачей отсортированы на странице в алфавитном порядке, в порядке возрастания

## Текущее поведение
Места приёма врачей отображаются в порядке использования и высвобождения 

## Шаги, чтобы воспроизвести проблему

  1. Открыть страницу врача
  2. Выбрать врача в списке

**Comment by VAlov223** [comment]
Сделано. Переоткрыть проблему, если не нравится, что сопутствующие кабинеты также принимают участие в сортировке среди фамилий врачей
